log:
  level: debug
  file: log/blog.log
server:
  appModel: debug
  httpPort: :8080
blog:
  host: 127.0.0.1
  port: 3306
  dbName: ginblog
  userName: root
  password: a12Cd3_45pUq6
redis:
  addr: 127.0.0.1:6379
  db: 0
  pass:
qiniu:
  accessKey: NlLBHAWaYAy8PkxxEBpkBGXJk7Adb9ZKmVkG6MkG
  secretKey: NypL0GsrYvcQu6A6HSYgePadl8NaAwnPKeee8CUW
  bucket: donkor-ginblog
  qiniuServer: http://sivnjg2g0.hn-bkt.clouddn.com/